INSERT INTO ALOJAMIENTO (ID, CAPACIDAD, TIPO, OPERADOR_ID, REGISTRO_CAM, REGISTRO_SUP, UBICACION, DESCRIPCION)
VALUES (1, 1, 1, 1, 'REGISTR_CAM', 'REGISTRO_SUP', 'UBICACION', 'DESCRIPCION');

INSERT INTO OFERTA (ID, DIA, PRECIO, ALOJAMIENTO_ID)
VALUES (1, TO_DATE('11-11-2020','DD-MM-YYYY') , 1, 1);
