INSERT INTO USUARIO (ID, USUARIO, CORREO, CONTRASENA, NUMERO_DOCUMENTO, TIPO_DOCUMENTO) 
VALUES (1, 'USUARIO', 'CORREO', 'CONTRASENA', 1, 1);

INSERT INTO CLIENTE (ID, NOMBRE, ROL) 
VALUES (1, 'NOMBRE', 1);