SELECT AL.* FROM OFERTA OFE JOIN ALOJAMIENTO AL ON OFE.ALOJAMIENTO_ID=AL.ID JOIN (  SELECT AL.ID	
FROM ALOJAMIENTO AL 
JOIN SERVICIOS_ALOJAMIENTOS SA ON AL.ID= sa.alojamiento_id 
JOIN SERVICIO SER ON sa.servicio_id=SER.ID 
WHERE SER.DESCRIPCION LIKE 'DESCRIPCION 1' OR SER.DESCRIPCION LIKE 'DESCRIPCION2'
GROUP BY AL.ID 
HAVING COUNT(*) = 2 ) INFO ON INFO.ID=AL.ID 
WHERE OFE.DIA<TO_DATE('2020-11-11','YYYY-MM-DD')  AND OFE.DIA>TO_DATE('2020-01-01','YYYY-MM-DD');